
-- 1. Add frequency and start date to installment_plans
ALTER TABLE installment_plans 
ADD COLUMN IF NOT EXISTS payment_frequency TEXT CHECK (payment_frequency IN ('DIARIO', 'SEMANAL', 'QUINCENAL', 'MENSUAL')) DEFAULT 'SEMANAL';

ALTER TABLE installment_plans 
ADD COLUMN IF NOT EXISTS start_date DATE DEFAULT CURRENT_DATE;

-- 2. Create payment_records table for history
CREATE TABLE IF NOT EXISTS payment_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT REFERENCES installment_plans(id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    note TEXT
);

-- RLS for payment_records
ALTER TABLE payment_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert on payment_records" 
ON payment_records FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Allow public select on payment_records" 
ON payment_records FOR SELECT TO anon USING (true);
